services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: advanced_todo_api_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    image: redis:7.0-alpine
    environment:
      - REDIS_PASSWORD=your_redis_password
    command: ["redis-server", "--requirepass", "your_redis_password", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "your_redis_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    image: golang:1.24.5-alpine3.22
    working_dir: /app
    volumes:
      - .:/app
      - go-mod:/go/pkg/mod
    ports:
      - "3000:3000"
    command: ["go", "run", "./cmd/main.go"]
    restart: unless-stopped
    depends_on:
      - db
      - cache
    env_file:
      - .env

volumes:
  go-mod:
  db-data:
  redis-data: