CREATE TABLE users (
  id UUID PRIMARY KEY,
  fullname VARCHAR(255),
  role VARCHAR(10) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
  password VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL UNIQUE,
  is_email_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE todos (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP DEFAULT NULL
);